[tool.poetry]
name = "fastapi-todoapp"
version = "0.1.0"
description = ""
authors = ["Wania-Kazmi <waniakz019@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.110.0"
uvicorn = {extras = ["standard"], version = "^0.28.0"}
sqlmodel = "^0.0.16"
pytest = "^8.1.1"
httpx = "^0.27.0"
psycopg = {extras = ["binary"], version = "^3.1.18"}
psycopg2-binary = "^2.9.9"


[tool.poetry.group.dev.dependencies]
pytest-asyncio = "^0.23.5.post1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
